### ISSUE TITLE
BUG: ln: failed to create symbolic link (if folder exists)

### ISSUE THREAD

**Issue by tseemann** [denglab/SeqSero2#8]
Please check if the folder in `-d` exists before running?
Or use `ln -s -f` to force?

```
./SeqSero2_package.py -t 4 -i /path/contigs.fa -d 2018-20708 -p 8 -m k
ln: failed to create symbolic link ‘2018-20708/H_and_O_and_specific_genes.fasta’: File exists
ln: failed to create symbolic link ‘2018-20708/contigs.fa’: File exists
Traceback (most recent call last):
  File "./SeqSero2_package.py", line 1423, in <module>
    main()
  File "./SeqSero2_package.py", line 1248, in main
    subprocess.check_call("ln -sr "+dirpath+"/"+database+" "+" ".join(input_file)+" "+make_dir,shell=True)
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ln -sr /home/tseemann/git/SeqSero2/H_and_O_and_specific_genes.fasta /home/seq/MDU/QC/2018-20708/contigs.fa 2018-20708' returned non-zero exit status 1.
```

**Comment by Shaokang123** [comment]
Hi Torsten, all of them are good suggestions. We will begin to fix them and clean all bugs reports. Thanks.
